# Generated by Django 4.0.6 on 2022-07-14 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(blank=True, max_length=255, null=True)),
                ('updated_by', models.CharField(blank=True, max_length=255, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(blank=True, max_length=255, null=True)),
                ('updated_by', models.CharField(blank=True, max_length=255, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('title', models.CharField(max_length=255)),
                ('release_date', models.DateField(blank=True, null=True)),
                ('imdb_id', models.CharField(blank=True, max_length=255, null=True)),
                ('imdb_rating', models.FloatField(blank=True, null=True)),
                ('imdb_votes', models.IntegerField(blank=True, null=True)),
                ('imdb_url', models.URLField(blank=True, null=True)),
                ('poster_url', models.URLField(blank=True, null=True)),
                ('trailer_url', models.URLField(blank=True, null=True)),
                ('plot', models.TextField(blank=True, null=True)),
                ('director', models.CharField(blank=True, max_length=255, null=True)),
                ('writer', models.CharField(blank=True, max_length=255, null=True)),
                ('actors', models.CharField(blank=True, max_length=255, null=True)),
                ('runtime', models.IntegerField(blank=True, null=True)),
                ('language', models.CharField(blank=True, max_length=255, null=True)),
                ('country', models.CharField(blank=True, max_length=255, null=True)),
                ('genre', models.ManyToManyField(blank=True, to='movie_bank.genre')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
